name: Backend

on: [push]

defaults:
  run:
    working-directory: backend

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - name: fmt check
        run: sbt fmtCheck
  test:
    runs-on: ubuntu-latest
    container: hseeberger/scala-sbt:8u265_1.4.3_2.13.3
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - name: test
        run: sbt test
