name: Backend

on: [push]

defaults:
  run:
    working-directory: backend

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - name: fmt check
        run: sbt fmtCheck
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Coursier cache
        uses: coursier/cache-action@v5
      - name: setup-scala
        uses: olafurpg/setup-scala@v10
      - name: test
        run: sbt test
